/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Spieler;
import bl.BombController;
import java.awt.Color;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JToggleButton;

/**
 *
 * @author Kevin
 */
public class BombsGUI extends javax.swing.JFrame {

    BombController bc = new BombController();
    int score = 1;

    Spieler s = null;

    public Spieler getS() {
        return s;
    }

    public void setS(Spieler s) {
        this.s = s;
        lbName.setText("Name: " + s.getName());
        lbGeld.setText(String.format("Geld: %.0f Chips", s.getGeld() * 5));
        lbIcon.setIcon(s.getIcon().getIcon());
    }

    public BombsGUI() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setUndecorated(true);
        initComponents();
        JToggleButton[][] tbfield = {
            {bt00, bt01, bt02, bt03, bt04},
            {bt10, bt11, bt12, bt13, bt14},
            {bt20, bt21, bt22, bt23, bt24},
            {bt30, bt31, bt32, bt33, bt34},
            {bt40, bt41, bt42, bt43, bt44}
        };

        JLabel[] spaltenfield = {lbS0, lbS1, lbS2, lbS3, lbS4};
        JLabel[] zeilenfield = {lbZ0, lbZ1, lbZ2, lbZ3, lbZ4};

        for (int i = 0; i < tbfield.length; i++) {
            for (int j = 0; j < tbfield.length; j++) {
                tbfield[i][j].setName(i + " " + j);

            }

        }
        bc.setZeilenfield(zeilenfield);
        bc.setSpaltenfield(spaltenfield);
        bc.setButtons(tbfield);
        bc.fillfield(tbfield);
        btNew.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        btNew = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbS0 = new javax.swing.JLabel();
        lbS1 = new javax.swing.JLabel();
        lbS2 = new javax.swing.JLabel();
        lbS3 = new javax.swing.JLabel();
        lbS4 = new javax.swing.JLabel();
        tfScore = new javax.swing.JTextField();
        bt00 = new javax.swing.JToggleButton();
        bt01 = new javax.swing.JToggleButton();
        bt02 = new javax.swing.JToggleButton();
        bt03 = new javax.swing.JToggleButton();
        bt04 = new javax.swing.JToggleButton();
        lbZ0 = new javax.swing.JLabel();
        bt10 = new javax.swing.JToggleButton();
        bt11 = new javax.swing.JToggleButton();
        bt12 = new javax.swing.JToggleButton();
        bt13 = new javax.swing.JToggleButton();
        bt14 = new javax.swing.JToggleButton();
        lbZ1 = new javax.swing.JLabel();
        bt20 = new javax.swing.JToggleButton();
        bt21 = new javax.swing.JToggleButton();
        bt22 = new javax.swing.JToggleButton();
        bt23 = new javax.swing.JToggleButton();
        bt24 = new javax.swing.JToggleButton();
        lbZ2 = new javax.swing.JLabel();
        bt30 = new javax.swing.JToggleButton();
        bt31 = new javax.swing.JToggleButton();
        bt32 = new javax.swing.JToggleButton();
        bt33 = new javax.swing.JToggleButton();
        bt34 = new javax.swing.JToggleButton();
        lbZ3 = new javax.swing.JLabel();
        bt40 = new javax.swing.JToggleButton();
        bt41 = new javax.swing.JToggleButton();
        bt42 = new javax.swing.JToggleButton();
        bt43 = new javax.swing.JToggleButton();
        bt44 = new javax.swing.JToggleButton();
        lbZ4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbIcon = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbName = new javax.swing.JLabel();
        lbGeld = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KevBombs");

        jPanel4.setLayout(new java.awt.GridLayout(2, 0));

        btNew.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        btNew.setText("Neues Spiel");
        btNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onNewGame(evt);
            }
        });
        jPanel4.add(btNew);

        jButton1.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        jButton1.setText("Zurück");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onBack(evt);
            }
        });
        jPanel4.add(jButton1);

        getContentPane().add(jPanel4, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(6, 6));

        lbS0.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        lbS0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbS0.setText("0");
        lbS0.setOpaque(true);
        jPanel1.add(lbS0);

        lbS1.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        lbS1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbS1.setText("0");
        lbS1.setOpaque(true);
        jPanel1.add(lbS1);

        lbS2.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        lbS2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbS2.setText("0");
        lbS2.setOpaque(true);
        jPanel1.add(lbS2);

        lbS3.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        lbS3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbS3.setText("0");
        lbS3.setOpaque(true);
        jPanel1.add(lbS3);

        lbS4.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        lbS4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbS4.setText("0");
        lbS4.setOpaque(true);
        jPanel1.add(lbS4);

        tfScore.setEditable(false);
        tfScore.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        tfScore.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfScore.setText("1");
        jPanel1.add(tfScore);

        bt00.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        bt00.setText("?");
        bt00.setFocusable(false);
        bt00.setName("0,0"); // NOI18N
        bt00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFlip(evt);
            }
        });
        jPanel1.add(bt00);

        bt01.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        bt01.setText("?");
        bt01.setFocusable(false);
        bt01.setName("0,1"); // NOI18N
        bt01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFlip(evt);
            }
        });
        jPanel1.add(bt01);

        bt02.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        bt02.setText("?");
        bt02.setFocusable(false);
        bt02.setName("0,2"); // NOI18N
        bt02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFlip(evt);
            }
        });
        jPanel1.add(bt02);

        bt03.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        bt03.setText("?");
        bt03.setFocusable(false);
        bt03.setName("0,3"); // NOI18N
        bt03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFlip(evt);
            }
        });
        jPanel1.add(bt03);

        bt04.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        bt04.setText("?");
        bt04.setFocusable(false);
        bt04.setName("0,4"); // NOI18N
        bt04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFlip(evt);
            }
        });
        jPanel1.add(bt04);

        lbZ0.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        lbZ0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbZ0.setText("0");
        lbZ0.setOpaque(true);
        jPanel1.add(lbZ0);

        bt10.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        bt10.setText("?");
        bt10.setFocusable(false);
        bt10.setName("1,0"); // NOI18N
        bt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFlip(evt);
            }
        });
        jPanel1.add(bt10);

        bt11.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        bt11.setText("?");
        bt11.setFocusable(false);
        bt11.setName("1,1"); // NOI18N
        bt11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFlip(evt);
            }
        });
        jPanel1.add(bt11);

        bt12.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        bt12.setText("?");
        bt12.setFocusable(false);
        bt12.setName("1,2"); // NOI18N
        bt12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFlip(evt);
            }
        });
        jPanel1.add(bt12);

        bt13.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        bt13.setText("?");
        bt13.setFocusable(false);
        bt13.setName("1,3"); // NOI18N
        bt13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFlip(evt);
            }
        });
        jPanel1.add(bt13);

        bt14.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        bt14.setText("?");
        bt14.setFocusable(false);
        bt14.setName("1,4"); // NOI18N
        bt14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFlip(evt);
            }
        });
        jPanel1.add(bt14);

        lbZ1.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        lbZ1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbZ1.setText("0");
        lbZ1.setOpaque(true);
        jPanel1.add(lbZ1);

        bt20.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        bt20.setText("?");
        bt20.setFocusable(false);
        bt20.setName("2,0"); // NOI18N
        bt20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFlip(evt);
            }
        });
        jPanel1.add(bt20);

        bt21.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        bt21.setText("?");
        bt21.setFocusable(false);
        bt21.setName("2,1"); // NOI18N
        bt21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFlip(evt);
            }
        });
        jPanel1.add(bt21);

        bt22.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        bt22.setText("?");
        bt22.setFocusable(false);
        bt22.setName("2,2"); // NOI18N
        bt22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFlip(evt);
            }
        });
        jPanel1.add(bt22);

        bt23.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        bt23.setText("?");
        bt23.setFocusable(false);
        bt23.setName("2,3"); // NOI18N
        bt23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFlip(evt);
            }
        });
        jPanel1.add(bt23);

        bt24.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        bt24.setText("?");
        bt24.setFocusable(false);
        bt24.setName("2,4"); // NOI18N
        bt24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFlip(evt);
            }
        });
        jPanel1.add(bt24);

        lbZ2.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        lbZ2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbZ2.setText("0");
        lbZ2.setOpaque(true);
        jPanel1.add(lbZ2);

        bt30.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        bt30.setText("?");
        bt30.setFocusable(false);
        bt30.setName("3,0"); // NOI18N
        bt30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFlip(evt);
            }
        });
        jPanel1.add(bt30);

        bt31.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        bt31.setText("?");
        bt31.setFocusable(false);
        bt31.setName("3,1"); // NOI18N
        bt31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFlip(evt);
            }
        });
        jPanel1.add(bt31);

        bt32.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        bt32.setText("?");
        bt32.setFocusable(false);
        bt32.setName("3,2"); // NOI18N
        bt32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFlip(evt);
            }
        });
        jPanel1.add(bt32);

        bt33.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        bt33.setText("?");
        bt33.setFocusable(false);
        bt33.setName("3,3"); // NOI18N
        bt33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFlip(evt);
            }
        });
        jPanel1.add(bt33);

        bt34.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        bt34.setText("?");
        bt34.setFocusable(false);
        bt34.setName("3,4"); // NOI18N
        bt34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFlip(evt);
            }
        });
        jPanel1.add(bt34);

        lbZ3.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        lbZ3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbZ3.setText("0");
        lbZ3.setOpaque(true);
        jPanel1.add(lbZ3);

        bt40.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        bt40.setText("?");
        bt40.setFocusable(false);
        bt40.setName("4,0"); // NOI18N
        bt40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFlip(evt);
            }
        });
        jPanel1.add(bt40);

        bt41.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        bt41.setText("?");
        bt41.setFocusable(false);
        bt41.setName("4,1"); // NOI18N
        bt41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFlip(evt);
            }
        });
        jPanel1.add(bt41);

        bt42.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        bt42.setText("?");
        bt42.setFocusable(false);
        bt42.setName("4,2"); // NOI18N
        bt42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFlip(evt);
            }
        });
        jPanel1.add(bt42);

        bt43.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        bt43.setText("?");
        bt43.setFocusable(false);
        bt43.setName("4,3"); // NOI18N
        bt43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFlip(evt);
            }
        });
        jPanel1.add(bt43);

        bt44.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        bt44.setText("?");
        bt44.setFocusable(false);
        bt44.setName("4,4"); // NOI18N
        bt44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFlip(evt);
            }
        });
        jPanel1.add(bt44);

        lbZ4.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        lbZ4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbZ4.setText("0");
        lbZ4.setOpaque(true);
        jPanel1.add(lbZ4);

        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.BorderLayout());

        lbIcon.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        lbIcon.setOpaque(true);
        jPanel3.add(lbIcon, java.awt.BorderLayout.WEST);

        jPanel7.setLayout(new java.awt.GridLayout(2, 0, 10, 0));

        lbName.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        lbName.setText("Name:");
        lbName.setOpaque(true);
        jPanel7.add(lbName);

        lbGeld.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        lbGeld.setText("Geld:");
        lbGeld.setOpaque(true);
        jPanel7.add(lbGeld);

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onFlip(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onFlip
        JToggleButton button = (JToggleButton) evt.getSource();
        String buttonname = button.getName();
        int val = bc.flip(buttonname);
        if (val == 0) {
            tfScore.setText("Game Over (" + score + ")");
            score = 1;
            button.setText("");
            button.setIcon(new ImageIcon(System.getProperty("user.dir") + File.separator + "src" + File.separator + "images" + File.separator + "Bomb.png"));
            button.setBackground(Color.RED);
            bc.gameOver();
            btNew.setEnabled(true);
        } else if (val == -1) {
            tfScore.setText("Gewonnen (" + score + ")");
            bc.gameOver();
            btNew.setEnabled(true);
        } else {
            score = score + val;
            s.setGeld(s.getGeld() + val);
            tfScore.setText(score + "");
            button.setText(val + "");
        }
        button.setEnabled(false);
        updateUI();
    }//GEN-LAST:event_onFlip

    private void onNewGame(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onNewGame
        btNew.setEnabled(false);
        tfScore.setText(score + "");
        bc.newGame();
        if (s.getGeld() >= 100) {
            s.setGeld(s.getGeld() - 20);
        }
        updateUI();
    }//GEN-LAST:event_onNewGame

    private void onBack(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onBack
        MenuGUI menugui = new MenuGUI();
        s.setGeld(s.getGeld());
        menugui.setS(s);
        menugui.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_onBack

    public void updateUI() {
        lbGeld.setText(String.format("Geld: %.0f Chips", s.getGeld() * 5));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BombsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BombsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BombsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BombsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BombsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bt00;
    private javax.swing.JToggleButton bt01;
    private javax.swing.JToggleButton bt02;
    private javax.swing.JToggleButton bt03;
    private javax.swing.JToggleButton bt04;
    private javax.swing.JToggleButton bt10;
    private javax.swing.JToggleButton bt11;
    private javax.swing.JToggleButton bt12;
    private javax.swing.JToggleButton bt13;
    private javax.swing.JToggleButton bt14;
    private javax.swing.JToggleButton bt20;
    private javax.swing.JToggleButton bt21;
    private javax.swing.JToggleButton bt22;
    private javax.swing.JToggleButton bt23;
    private javax.swing.JToggleButton bt24;
    private javax.swing.JToggleButton bt30;
    private javax.swing.JToggleButton bt31;
    private javax.swing.JToggleButton bt32;
    private javax.swing.JToggleButton bt33;
    private javax.swing.JToggleButton bt34;
    private javax.swing.JToggleButton bt40;
    private javax.swing.JToggleButton bt41;
    private javax.swing.JToggleButton bt42;
    private javax.swing.JToggleButton bt43;
    private javax.swing.JToggleButton bt44;
    private javax.swing.JButton btNew;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbGeld;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbS0;
    private javax.swing.JLabel lbS1;
    private javax.swing.JLabel lbS2;
    private javax.swing.JLabel lbS3;
    private javax.swing.JLabel lbS4;
    private javax.swing.JLabel lbZ0;
    private javax.swing.JLabel lbZ1;
    private javax.swing.JLabel lbZ2;
    private javax.swing.JLabel lbZ3;
    private javax.swing.JLabel lbZ4;
    private javax.swing.JTextField tfScore;
    // End of variables declaration//GEN-END:variables
}
