/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Spieler;
import database.DB_Access;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Kevin
 */
public class LoginGUI extends javax.swing.JFrame {

    public LoginGUI() {

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setUndecorated(true);
        initComponents();
        paRegister.setVisible(false);
        paLogin.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btLogin = new javax.swing.JButton();
        paLogin = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        paLoginPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pfLogin = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        btRegister = new javax.swing.JButton();
        paRegister = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        paRegisterPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfRegister = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pfRegister = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        pfRegister2 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SlotPark");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(3, 0));

        jPanel2.setLayout(new java.awt.CardLayout());

        btLogin.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btLogin.setText("Login");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onLogin(evt);
            }
        });
        jPanel2.add(btLogin, "card2");

        paLogin.setLayout(new java.awt.BorderLayout());

        jButton4.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        jButton4.setText("Login");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onRealLogin(evt);
            }
        });
        paLogin.add(jButton4, java.awt.BorderLayout.SOUTH);

        paLoginPanel.setLayout(new java.awt.GridLayout(2, 1));

        jLabel2.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        jLabel2.setText("User:");
        paLoginPanel.add(jLabel2);

        tfLogin.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        paLoginPanel.add(tfLogin);

        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        jLabel3.setText("Password:");
        paLoginPanel.add(jLabel3);

        pfLogin.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        paLoginPanel.add(pfLogin);

        paLogin.add(paLoginPanel, java.awt.BorderLayout.CENTER);

        jPanel2.add(paLogin, "card3");

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.CardLayout());

        btRegister.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btRegister.setText("Register");
        btRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onRegister(evt);
            }
        });
        jPanel3.add(btRegister, "card3");

        paRegister.setLayout(new java.awt.BorderLayout());

        jButton5.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        jButton5.setText("Registrieren");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onRealRegister(evt);
            }
        });
        paRegister.add(jButton5, java.awt.BorderLayout.SOUTH);

        paRegisterPanel.setLayout(new java.awt.GridLayout(3, 1));

        jLabel4.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        jLabel4.setText("User:");
        paRegisterPanel.add(jLabel4);

        tfRegister.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        paRegisterPanel.add(tfRegister);

        jLabel5.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        jLabel5.setText("Password:");
        paRegisterPanel.add(jLabel5);

        pfRegister.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        paRegisterPanel.add(pfRegister);

        jLabel6.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        jLabel6.setText("Password bestätigen:");
        paRegisterPanel.add(jLabel6);

        pfRegister2.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        paRegisterPanel.add(pfRegister2);

        paRegister.add(paRegisterPanel, java.awt.BorderLayout.CENTER);

        jPanel3.add(paRegister, "card3");

        jPanel1.add(jPanel3);

        jButton3.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onExit(evt);
            }
        });
        jPanel1.add(jButton3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onExit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onExit
        this.dispose();
    }//GEN-LAST:event_onExit

    private void onLogin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onLogin
        btLogin.setVisible(false);
        paLogin.setVisible(true);
        btRegister.setVisible(true);
        paRegister.setVisible(false);
    }//GEN-LAST:event_onLogin

    private void onRealLogin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onRealLogin
        String user = tfLogin.getText();
        String password = pfLogin.getText();
        Spieler spieler;
    }//GEN-LAST:event_onRealLogin

    private void onRealRegister(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onRealRegister
        boolean checkuser = false;
        boolean checkpassword = false;
        String user = tfRegister.getText();
        String password = pfRegister.getText();
        String password2 = pfRegister2.getText();
        if (!user.isEmpty() && !user.contains(" ")) {
            tfRegister.setBackground(Color.WHITE);
            checkuser = true;
        } else {
            tfRegister.setBackground(Color.red);
        }

        if (!password.isEmpty() && !password.contains(" ") && password.equals(password2)) {
            pfRegister.setBackground(Color.white);
            checkpassword = true;
        } else {
            pfRegister.setBackground(Color.red);
            pfRegister2.setBackground(Color.RED);
        }

        if (checkpassword && checkuser) {
            MenuGUI menugui = new MenuGUI();
            menugui.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_onRealRegister

    private void onRegister(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onRegister
        btRegister.setVisible(false);
        paRegister.setVisible(true);
        btLogin.setVisible(true);
        paLogin.setVisible(false);
    }//GEN-LAST:event_onRegister

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btRegister;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel paLogin;
    private javax.swing.JPanel paLoginPanel;
    private javax.swing.JPanel paRegister;
    private javax.swing.JPanel paRegisterPanel;
    private javax.swing.JPasswordField pfLogin;
    private javax.swing.JPasswordField pfRegister;
    private javax.swing.JPasswordField pfRegister2;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JTextField tfRegister;
    // End of variables declaration//GEN-END:variables
}
